services:
  - type: web
    name: cognitosense-backend
    runtime: node
    startCommand: npm start
    buildCommand: npm install --prefix server && npm run build --prefix server
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
    region: oregon
